version: "3.1"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: sqlx
    ports:
      - 5432:5432